//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesTransactionInvoice
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesTransaction
    {
        public int Sales_ID { get; set; }
        public int Customer_ID { get; set; }
        public int Product_ITEMID { get; set; }
        public decimal Product_QUANTITY { get; set; }
        public decimal Product_TOTAL { get; set; }
        public string Sales_STATUS { get; set; }
        public string Sales_DESCR { get; set; }
        public System.DateTime Sales_PURCHASEDATE { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
    }
}
